добавил форму для ввода слова
Ilyaivanov60/web_dictionary pull request #4
Opened 2020-12-17 12:04 UTC by Ilyaivanov60

В файле routes.py не могу обработать if form.validate_on_submit(), для входа в условие.

2020-12-18 13:04 UTC, alexandrettio requested changes

2020-12-18 13:04 UTC, alexandrettio commented on webapp/forms.py
> +    word_for_translate = StringField('Введите слово для перевода', validators=[DataRequired()])
Меня очень смущает, что это класс LoginForm.
Кажется что форма добавления нового слова это отдельная сущность

2020-12-18 13:04 UTC, alexandrettio commented on webapp/routes.py
> +    form = LoginForm()
Ну и тут соответственно отголосок того что это не форма для логин, аналогично надо поменять

2020-12-18 13:04 UTC, alexandrettio commented on webapp/routes.py
> +    global cards
О. расскажи почему решил воспользоваться global переменной

2020-12-18 13:04 UTC, alexandrettio commented on webapp/routes.py
> +            cards += [word]
Обычно используют cards.append(word)
Твой способ может работать медленнее (но не факт так как возможны внутренние оптимизации)

2020-12-18 13:04 UTC, alexandrettio commented on webapp/routes.py
> +    return render_template('index.html', title='Home', user=user, cards=cards, form=form)
У тебя получилось что ты делаешь два одинаковых return. 
Давай оставим только внешний и проверим, что ничего не сломали

2020-12-20 12:56 UTC, Ilyaivanov60 commented on webapp/routes.py
> +    global cards
Программа падала, не видела cards. Пришлось явно показать где искать cards, сейчас все поправил и заработала)

2021-01-14 12:39 UTC, alexandrettio approved these changes

2021-01-14 12:47 UTC, Ilyaivanov60 commented
добавил форму для ввода слова

2021-01-14 12:48 UTC, merged